DROP TABLE IF EXISTS events CASCADE;

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category           BIGINT REFERENCES categories (id) ON DELETE RESTRICT,
    initiator          BIGINT REFERENCES users (id) ON DELETE CASCADE,
    annotation         VARCHAR(1000),
    description        VARCHAR(2000),
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    location           BIGINT REFERENCES locations (id) ON DELETE CASCADE,
    paid               BOOLEAN,
    participant_limit  INTEGER,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    state              VARCHAR(15),
    title              VARCHAR(100)
);

DROP TABLE IF EXISTS events_to_compilations CASCADE;

CREATE TABLE IF NOT EXISTS events_to_compilations
(
    event_id       BIGINT REFERENCES events (id) ON DELETE CASCADE,
    compilation_id BIGINT REFERENCES compilations (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS requests CASCADE;

CREATE TABLE IF NOT EXISTS requests
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester BIGINT REFERENCES users (id) ON DELETE CASCADE,
    event     BIGINT REFERENCES events (id) ON DELETE CASCADE,
    created   VARCHAR(30),
    status    VARCHAR(15) NOT NULL
);