version: '3.8'
services:
  stats-server:
    build: ewm-stats-service/server
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  stats-db:
    image: postgres:14.6-alpine
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  main-service:
    build: ./ewm-main-service
    image: main-service-image
    container_name: main_service_container
    ports:
      - "8080:8080"
    depends_on:
      - db-main
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-main:5432/ewm-main-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  db-main:
    image: postgres:14.4-alpine
    container_name: main_service_db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=main_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot