version: '3.1'
services:
  stats-server:
    build: ewm-stats-service/server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - STATS_SERVER_URL=http://server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
    networks:
      - ewm-network

  stats-db:
    image: postgres:15
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot
    networks:
      - ewm-network

  ewm-service:
    build: ewm-main-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    environment:
      - EWM_SERVICE_URL=http://server:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/postgres
    networks:
      - ewm-network

  ewm-db:
    image: postgres:15
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot
    networks:
      - ewm-network

networks:
  ewm-network:
    driver: bridge