version: '3.1'
services:
  stats-server:
    build: ewm-stats-service/server
    image: ewm-stats-service
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - EWM_STATS_SERVER_URL=http://server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres

  stats-db:
    image: postgres:15
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot

  ewm-service:
    build: ewm-main-service
    image: ewm-main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - EWM_MAIN_SERVICE_URL=http://server:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5433/postgres

  ewm-db:
    image: postgres:15
    container_name: ewm-db
    ports:
      - "6542:5433"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot